### ISSUE TITLE
[TASK] Negative tests for handler contracts

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-ink#72]
## Overview
We need to add additional negative tests for each contract handler.

## Task Checklist

- [ ] Negative tests for anchorHandler
- [ ] Negative tests for treasuryHandler
- [ ] Negative tests for tokenWrapperHandler

### Relevant Links
