### ISSUE TITLE
[TASK] Add tests for VAnchor 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-ink#73]
## Overview
The VAnchor is currently not tested well enough. We need to add tests for deposit, withdraw and negative tests for both psp22 and native assets. 

## Task Checklist

- [ ] Add tests for deposit with psp22
- [ ] Add tests for withdraw with psp22
- [ ] Add tests for deposit with native asset
- [ ] Add tests for withdraw with native asset
- [ ] Add negative tests 

### Relevant Links
